packages/mcs-lite-design/src/icon/icon_pause.svg, packages/mcs-lite-design/src/icon/icon_play.svg
=> feat(Design): add new Pause, Play, Refresh icons

packages/mcs-lite-design/src/icon/icon_logout.svg, packages/mcs-lite-design/src/icon/icon_sync.svg
=> feat(Design): Add new Logout, Sync icons

packages/eslint-config-mcs-lite/index.js, packages/eslint-config-mcs-lite/package.json, packages/mcs-lite-mobile-web/src/components/WebSocketNotification/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/Account/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/App/App.js, packages/mcs-lite-mobile-web/src/containers/App/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceDataChannelDetail/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceDataChannelTimeRange/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceDetail/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceDetailInfo/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceList/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceTrigger/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceTriggerEdit/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/Password/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/containers/Signin/__tests__/messages.test.js, packages/mcs-lite-mobile-web/src/store/configureStore.js, packages/mcs-lite-mobile-web/src/utils/updatePathname.js, packages/mcs-lite-ui/src/Button/Button.js, packages/mcs-lite-ui/src/DataChannelAdapter/DataChannelAdapter.js, packages/mcs-lite-ui/src/Dialog/Dialog.js, packages/mcs-lite-ui/src/Heading/Heading.js, packages/mcs-lite-ui/src/MobileHeader/MobileHeaderIcon.js, packages/mcs-lite-ui/src/P/P.js, packages/mcs-lite-ui/src/Select/Select.js, packages/mcs-lite-ui/src/Switch/Switch.example.js, packages/mcs-lite-ui/src/TabItem/TabItem.example.js, packages/mcs-lite-ui/src/Toast/Toast.js, packages/mcs-lite-ui/src/others/API.example.js
=> fix(eslint): remove useless old rules [BREAKING]

docs/licenses.csv, packages/mcs-lite-ui/.storybook/addons.js, packages/mcs-lite-ui/.storybook/config.js, packages/mcs-lite-ui/package.json, packages/mcs-lite-ui/src/Button/Button.js, packages/mcs-lite-ui/src/others/API.example.js
feat(storybook): add option add-on.
=> feat(storybook): add option add-on.

packages/mcs-lite-connect/package.json, packages/mcs-lite-connect/src/connectSocket.js, packages/mcs-lite-mobile-web/package.json, packages/mcs-lite-ui/package.json, packages/react-intl-inject-hoc/package.json
Remove `createHelper` of recompose
https://github.com/acdlite/recompose/issues/380
=> fix(recompose): update to 0.23.3

packages/mcs-lite-mobile-web/package.json, packages/mcs-lite-ui/package.json, packages/mcs-lite-ui/src/__tests__/__snapshots__/Storyshots.test.js.snap, packages/stylelint-config-mcs-lite/package.json, yarn.lock
BREAKING: update styled-components to 18
=> chore(styled-components): update 18 & storybook 3-alpha4

packages/mcs-lite-mobile-web/package.json
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#configuring-the-proxy-manually
=> fix(proxy): add custom proxy config with CRA 1.0.0

packages/mcs-lite-mobile-web/src/modules/__tests__/routing.test.js, packages/mcs-lite-mobile-web/src/modules/routing.js, packages/mcs-lite-mobile-web/src/utils/helpers.js, tasks/test.sh
fix(routing-cycle): there are some bugs when clone origin location object
=> fix(routing-cycle): there are some bugs when clone origin location object

packages/mcs-lite-admin-web/src/containers/System/styled-components.js
Lazy load css cause styling problem.
=> fix(Admin/Codemirror): Lazy load css cause styling problem.

packages/mcs-lite-translation/src/mcs-lite-admin-web/en.po, packages/mcs-lite-translation/src/mcs-lite-admin-web/zh-CN.po, packages/mcs-lite-translation/src/mcs-lite-admin-web/zh-TW.po, packages/mcs-lite-translation/src/mcs-lite-mobile-web/en.po, packages/mcs-lite-translation/src/mcs-lite-mobile-web/zh-CN.po, packages/mcs-lite-translation/src/mcs-lite-mobile-web/zh-TW.po
Update the *.po files for admin and mobile web.
=> feat(i18N): provide the translation strings for zh-CN and en.

packages/mcs-lite-design/src/icon/icon_stop.svg
=> feat(Icon): add new stop icon

packages/mcs-lite-admin-web/src/index.js, packages/mcs-lite-admin-web/src/modules/__tests__/routing.test.js, packages/mcs-lite-admin-web/src/modules/routing.js, packages/mcs-lite-admin-web/src/utils/__tests__/localeMapper.test.js, packages/mcs-lite-admin-web/src/utils/localeMapper.js, packages/mcs-lite-mobile-web/src/index.js, packages/mcs-lite-mobile-web/src/modules/__tests__/routing.test.js, packages/mcs-lite-mobile-web/src/modules/routing.js, packages/mcs-lite-mobile-web/src/utils/__tests__/localeMapper.test.js, packages/mcs-lite-mobile-web/src/utils/localeMapper.js
=> fix(i18n): add mapping locale rules

packages/mcs-lite-translation/src/mcs-lite-admin-web/en.po, packages/mcs-lite-translation/src/mcs-lite-admin-web/zh-CN.po, packages/mcs-lite-translation/src/mcs-lite-admin-web/zh-TW.po, packages/mcs-lite-translation/src/mcs-lite-mobile-web/en.po, packages/mcs-lite-translation/src/mcs-lite-mobile-web/zh-CN.po, packages/mcs-lite-translation/src/mcs-lite-mobile-web/zh-TW.po
Update the translation for new strings.
=> feat(i18N): update translation strings.

packages/mcs-lite-translation/src/mcs-lite-landing-web/zh-CN.po, packages/mcs-lite-translation/src/mcs-lite-landing-web/zh-TW.po
=> feat(i18N): update with proper translation strings.

packages/mcs-lite-admin-web/src/modules/auth.js, packages/mcs-lite-mobile-web/src/modules/auth.js
Issue:
ML-199
Update Rx operators
=> fix(Auth/Cycle): wrong Observable.of arguments

packages/mcs-lite-mobile-web/src/containers/DeviceDataChannelDetail/index.js, packages/mcs-lite-mobile-web/src/containers/DeviceDetail/index.js
Issue:
add support for wss SSL protocol
=> fix(Mobile): add support for wss SSL protocol

packages/mcs-lite-translation/src/mcs-lite-admin-web/en.po, packages/mcs-lite-translation/src/mcs-lite-admin-web/zh-CN.po, packages/mcs-lite-translation/src/mcs-lite-admin-web/zh-TW.po
Issue:
add translation strings for admin -> user management features.
=> feat(i18N): add translation for admin v2 feature.

packages/mcs-lite-admin-web/src/modules/__tests__/__snapshots__/service.test.js.snap, packages/mcs-lite-admin-web/src/modules/__tests__/__snapshots__/system.test.js.snap, packages/mcs-lite-admin-web/src/modules/__tests__/__snapshots__/users.test.js.snap, packages/mcs-lite-admin-web/src/modules/__tests__/service.test.js, packages/mcs-lite-admin-web/src/modules/__tests__/system.test.js, packages/mcs-lite-admin-web/src/modules/__tests__/users.test.js, packages/mcs-lite-admin-web/src/modules/users.js
=> fix(Admin): fix delete users cycle logic & add tests

packages/mcs-lite-admin-web/src/containers/DashboardLayout/DashboardLayout.js, packages/mcs-lite-admin-web/src/containers/DashboardLayout/__tests__/__snapshots__/DashboardLayout.test.js.snap, packages/mcs-lite-admin-web/src/containers/DashboardLayout/__tests__/__snapshots__/messages.test.js.snap, packages/mcs-lite-admin-web/src/containers/DashboardLayout/messages.js, packages/mcs-lite-admin-web/src/containers/Data/Data.js, packages/mcs-lite-admin-web/src/containers/Data/__tests__/Data.test.js, packages/mcs-lite-admin-web/src/containers/Data/__tests__/__snapshots__/Data.test.js.snap, packages/mcs-lite-admin-web/src/containers/Data/__tests__/__snapshots__/index.test.js.snap, packages/mcs-lite-admin-web/src/containers/Data/__tests__/__snapshots__/messages.test.js.snap, packages/mcs-lite-admin-web/src/containers/Data/__tests__/index.test.js, packages/mcs-lite-admin-web/src/containers/Data/__tests__/messages.test.js, packages/mcs-lite-admin-web/src/containers/Data/index.js, packages/mcs-lite-admin-web/src/containers/Data/messages.js, packages/mcs-lite-admin-web/src/index.js, packages/mcs-lite-admin-web/src/modules/__tests__/__snapshots__/data.test.js.snap, packages/mcs-lite-admin-web/src/modules/__tests__/auth.test.js, packages/mcs-lite-admin-web/src/modules/__tests__/data.test.js, packages/mcs-lite-admin-web/src/modules/auth.js, packages/mcs-lite-admin-web/src/modules/data.js, packages/mcs-lite-admin-web/src/modules/index.js, packages/mcs-lite-translation/src/mcs-lite-admin-web/messages.json, packages/mcs-lite-translation/src/mcs-lite-admin-web/messages.pot
=> feat(Admin/Data): add DeleteData feature

packages/mcs-lite-admin-web/src/containers/DashboardLayout/__tests__/DashboardLayout.test.js, packages/mcs-lite-admin-web/src/containers/Language/__tests__/Language.test.js, packages/mcs-lite-admin-web/src/containers/Language/__tests__/__snapshots__/Language.test.js.snap, packages/mcs-lite-admin-web/src/containers/Signup/__tests__/Signup.test.js, packages/mcs-lite-admin-web/src/containers/Signup/__tests__/__snapshots__/Signup.test.js.snap, packages/mcs-lite-admin-web/src/containers/System/System.js, packages/mcs-lite-admin-web/src/containers/System/__tests__/System.test.js, packages/mcs-lite-admin-web/src/containers/System/__tests__/__snapshots__/System.test.js.snap, packages/mcs-lite-admin-web/src/containers/System/__tests__/__snapshots__/styled-components.test.js.snap, packages/mcs-lite-admin-web/src/containers/System/__tests__/styled-components.test.js, packages/mcs-lite-admin-web/src/containers/User/Table.js, packages/mcs-lite-admin-web/src/containers/User/User.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/Table.test.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/User.test.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/Table.test.js.snap, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/User.test.js.snap, packages/mcs-lite-admin-web/src/utils/__tests__/__snapshots__/recomposeHelper.test.js.snap, packages/mcs-lite-admin-web/src/utils/__tests__/recomposeHelper.test.js, packages/mcs-lite-admin-web/src/utils/recomposeHelper.js
=> 	test(Admin): add more tests for container

packages/mcs-lite-admin-web/src/modules/__tests__/users.test.js, packages/mcs-lite-admin-web/src/modules/users.js
=> fix(Admin): wrong body format of delete user

packages/mcs-lite-design/src/icon/icon_edit.svg
=> feat(Icon): add new Edit icon

packages/mcs-lite-admin-web/src/components/DialogConfirm/DialogConfirm.js, packages/mcs-lite-admin-web/src/containers/User/Table.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/Table.test.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/Table.test.js.snap, packages/mcs-lite-admin-web/src/containers/User/styled-components.js, packages/mcs-lite-admin-web/src/modules/__tests__/__snapshots__/users.test.js.snap, packages/mcs-lite-admin-web/src/modules/__tests__/users.test.js, packages/mcs-lite-admin-web/src/modules/users.js, packages/mcs-lite-admin-web/src/utils/helpers.js, packages/mcs-lite-mobile-web/src/utils/helpers.js, packages/mcs-lite-ui/src/FormGroup/FormGroup.js, packages/mcs-lite-ui/src/__tests__/__snapshots__/Storyshots.test.js.snap
=> fix(Admin): do not refetch after users delete

docs/licenses.csv, packages/mcs-lite-admin-web/package.json, packages/mcs-lite-admin-web/src/modules/__tests__/users.test.js, packages/mcs-lite-admin-web/src/modules/users.js, yarn.lock
Issue:
https://github.com/MCS-Lite/mcs-lite-app/pull/188
=> 	fix(Admin/Use): post with CSV content

packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/styled-components.test.js.snap, packages/mcs-lite-admin-web/src/containers/User/__tests__/styled-components.test.js, packages/mcs-lite-admin-web/src/containers/User/styled-components.js
=> fix(Admin/User): update input file style

packages/mcs-lite-admin-web/src/containers/User/Table.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/Table.test.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/Table.test.js.snap
=> feat(Admin): table sort

packages/mcs-lite-admin-web/src/containers/User/User.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/User.test.js, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/User.test.js.snap, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/index.test.js.snap, packages/mcs-lite-admin-web/src/containers/User/__tests__/__snapshots__/messages.test.js.snap, packages/mcs-lite-admin-web/src/containers/User/__tests__/index.test.js, packages/mcs-lite-admin-web/src/containers/User/index.js, packages/mcs-lite-admin-web/src/containers/User/messages.js, packages/mcs-lite-admin-web/src/utils/__tests__/checkUserAvalableAPI.test.js, packages/mcs-lite-admin-web/src/utils/checkUserAvalableAPI.js, packages/mcs-lite-admin-web/src/utils/rxjs.js, packages/mcs-lite-translation/src/mcs-lite-admin-web/messages.json, packages/mcs-lite-translation/src/mcs-lite-admin-web/messages.pot
=> feat(Admin): add email async validation

packages/mcs-lite-landing-web/src/components/DownloadButton/DownloadButton.js, packages/mcs-lite-landing-web/src/components/DownloadButton/__tests__/DownloadButton.test.js, packages/mcs-lite-landing-web/src/components/DownloadButton/__tests__/__snapshots__/DownloadButton.test.js.snap, packages/mcs-lite-landing-web/src/containers/App/App.js, packages/mcs-lite-landing-web/src/containers/App/__tests__/__snapshots__/App.test.js.snap, packages/mcs-lite-landing-web/src/containers/Section1/Section1.js, packages/mcs-lite-landing-web/src/containers/Section1/__tests__/Section1.test.js, packages/mcs-lite-landing-web/src/containers/Section1/__tests__/__snapshots__/Section1.test.js.snap, packages/mcs-lite-landing-web/src/containers/Section5/Section5.js, packages/mcs-lite-landing-web/src/containers/Section5/__tests__/Section5.test.js, packages/mcs-lite-landing-web/src/containers/Section5/__tests__/__snapshots__/Section5.test.js.snap
=> feat(Landing): introduce micro-github-latest service for downloading the latest app

packages/mcs-lite-ui/.storybook/config.js
=> fix(UI/Storybook): Error when clicking on the menu item on React 16

packages/mcs-lite-admin-web/src/containers/Data/Data.js, packages/mcs-lite-admin-web/src/containers/Data/__tests__/__snapshots__/messages.test.js.snap, packages/mcs-lite-admin-web/src/containers/Data/messages.js, packages/mcs-lite-admin-web/src/modules/__tests__/__snapshots__/data.test.js.snap, packages/mcs-lite-admin-web/src/modules/__tests__/data.test.js, packages/mcs-lite-admin-web/src/modules/data.js, packages/mcs-lite-admin-web/src/modules/ui.js, packages/mcs-lite-translation/src/mcs-lite-admin-web/messages.json, packages/mcs-lite-translation/src/mcs-lite-admin-web/messages.pot
=> feat(Admin/Data): prompt restart when clear success

packages/mcs-lite-landing-web/package.json, yarn.lock
=> chore(Landing): update rc-scroll-anim 2.0

README.md, packages/mcs-lite-translation/package.json
=> test(translation): exit with error when there is fuzzy keywords

packages/mcs-lite-admin-web/src/modules/__tests__/ui.test.js, packages/mcs-lite-admin-web/src/modules/ui.js
=> fix(Admin): do not prompt restart notification when it is STOP now

.travis.yml
=> fix(Travis): yarn install with pure-lockfile

packages/babel-preset-mcs-lite/package.json, packages/mcs-lite-admin-web/package.json, packages/mcs-lite-landing-web/package.json, packages/mcs-lite-mobile-web/package.json, packages/mcs-lite-scripts/package.json, yarn.lock
=> chore(ncu): ncu update

packages/mcs-lite-mobile-web/src/containers/DeviceDataChannelDetail/DeviceDataChannelDetail.js, packages/mcs-lite-mobile-web/src/containers/DeviceDataChannelDetail/__tests__/DeviceDataChannelDetail.test.js, packages/mcs-lite-mobile-web/src/containers/DeviceDataChannelDetail/__tests__/__snapshots__/DeviceDataChannelDetail.test.js.snap
Issue:
https://github.com/MCS-Lite/mcs-lite-app/pull/223
=> fix(Mobile): hide history for some datachannels

packages/mcs-lite-landing-web/package.json, packages/mcs-lite-landing-web/src/components/DownloadButton/DownloadButton.js, packages/mcs-lite-landing-web/src/components/DownloadButton/__tests__/__snapshots__/index.test.js.snap, packages/mcs-lite-landing-web/src/components/DownloadButton/index.js, packages/mcs-lite-landing-web/src/containers/Section1/__tests__/__snapshots__/Section1.test.js.snap, packages/mcs-lite-landing-web/src/containers/Section5/__tests__/__snapshots__/Section5.test.js.snap, packages/mcs-lite-landing-web/src/index.js, yarn.lock
Download Button did not re-render with correct os info
Issue:
=> fix(Landing): We should use hydrate() here but got some problems with re-render

packages/mcs-lite-admin-web/package.json, packages/mcs-lite-landing-web/package.json, packages/mcs-lite-mobile-web/package.json, yarn.lock
=> chore(ncu): upgrade react-intl-cra

packages/mcs-lite-ui/setupTests.js, packages/mcs-lite-ui/src/Breadcrumb/Breadcrumb.example.js, packages/mcs-lite-ui/src/Breadcrumb/Breadcrumb.js, packages/mcs-lite-ui/src/Breadcrumb/__snapshots__/Breadcrumb.example.storyshot, packages/mcs-lite-ui/src/Breadcrumb/index.js, packages/mcs-lite-ui/src/Form/ErrorMessage.js, packages/mcs-lite-ui/src/Form/Fieldset.js, packages/mcs-lite-ui/src/Form/Form.example.js, packages/mcs-lite-ui/src/Form/__snapshots__/Form.example.storyshot, packages/mcs-lite-ui/src/Form/index.js, packages/mcs-lite-ui/src/LandingHeader/__snapshots__/LandingHeader.example.storyshot, packages/mcs-lite-ui/src/Menu/__snapshots__/Menu.example.storyshot, packages/mcs-lite-ui/src/Notification/__snapshots__/Notification.example.storyshot, packages/mcs-lite-ui/src/P/__snapshots__/P.example.storyshot, packages/mcs-lite-ui/src/Small/__snapshots__/Small.example.storyshot, packages/mcs-lite-ui/src/Toast/__snapshots__/Toast.example.storyshot
=> feat(UI): add Breadcrumb component & ErrorMessage in Form

packages/mcs-lite-ui/src/Form/Form.example.js, packages/mcs-lite-ui/src/Form/__snapshots__/Form.example.storyshot, packages/mcs-lite-ui/src/ImageDropzone/Container.js, packages/mcs-lite-ui/src/ImageDropzone/ImageDropzone.js, packages/mcs-lite-ui/src/ImageDropzone/LoadingWrapper.js, packages/mcs-lite-ui/src/ImageDropzone/__snapshots__/ImageDropzone.example.storyshot, packages/mcs-lite-ui/src/LandingHeader/__snapshots__/LandingHeader.example.storyshot, packages/mcs-lite-ui/src/Menu/__snapshots__/Menu.example.storyshot, packages/mcs-lite-ui/src/Notification/__snapshots__/Notification.example.storyshot, packages/mcs-lite-ui/src/P/__snapshots__/P.example.storyshot, packages/mcs-lite-ui/src/Small/__snapshots__/Small.example.storyshot, packages/mcs-lite-ui/src/Spin/__snapshots__/Spin.example.storyshot, packages/mcs-lite-ui/src/Toast/__snapshots__/Toast.example.storyshot, packages/mcs-lite-ui/src/others/__snapshots__/Icon.example.storyshot
Issue:
The red star should be placed in the last line.
=> fix(UI): label required star position & update ImageDropzone loading style

packages/mcs-lite-ui/src/InputSelect/__snapshots__/InputSelect.example.storyshot, packages/mcs-lite-ui/src/Select/__snapshots__/Select.example.storyshot, packages/mcs-lite-ui/src/Select/styled-components.js
=> fix(UI): select svg icon size

dangerfile.js
=> fix(danger): update dangerfile

packages/mcs-lite-ui/src/InputSelect/InputSelect.js, packages/mcs-lite-ui/src/InputSelect/styled-components.js
=> fix(UI): add text-overflow style in InputSelect Component

package.json, packages/eslint-config-mcs-lite/index.js, packages/eslint-config-mcs-lite/package.json, packages/mcs-lite-ui/src/InputCheckbox/InputCheckbox.example.js, packages/mcs-lite-ui/src/InputCheckbox/__snapshots__/InputCheckbox.example.storyshot, packages/mcs-lite-ui/src/InputMultiSelect/InputMultiSelect.example.js, packages/mcs-lite-ui/src/InputMultiSelect/InputMultiSelect.js, packages/mcs-lite-ui/src/InputMultiSelect/__snapshots__/InputMultiSelect.example.storyshot, packages/mcs-lite-ui/src/InputMultiSelect/index.js, packages/mcs-lite-ui/src/InputOrder/InputOrder.example.js, packages/mcs-lite-ui/src/InputOrder/InputOrder.js, yarn.lock
=> feat(ui): add InputMultiSelect Component

packages/mcs-lite-ui/src/Table/Table.js, packages/mcs-lite-ui/src/Table/__snapshots__/Table.example.storyshot
=> fix(ui): table th font-weight

packages/mcs-lite-design/src/icon/icon_data.svg, packages/mcs-lite-design/src/icon/icon_data_usage.svg, packages/mcs-lite-design/src/icon/icon_export.svg, packages/mcs-lite-design/src/icon/icon_notification.svg, packages/mcs-lite-design/src/icon/icon_on_premise.svg, packages/mcs-lite-design/src/icon/icon_richer_trigger_rules.svg, packages/mcs-lite-design/src/icon/icon_scene.svg, packages/mcs-lite-design/src/icon/icon_unlimited.svg
=> feat(icon): add 8 new icons

packages/mcs-lite-ui/src/InputMultiSelect/InputMultiSelect.js, packages/mcs-lite-ui/src/InputMultiSelect/__snapshots__/InputMultiSelect.example.storyshot, packages/mcs-lite-ui/src/InputOrder/__snapshots__/InputOrder.example.storyshot, packages/mcs-lite-ui/src/InputOrder/styled-components.js
=> fix(ui): update Icons size in InputMultiSelect Component

packages/mcs-lite-ui/src/InputMultiSelect/InputMultiSelect.js, packages/mcs-lite-ui/src/InputMultiSelect/__snapshots__/InputMultiSelect.example.storyshot, packages/mcs-lite-ui/src/InputOrder/InputOrder.js
=> fix(ui): tuning InputMultiSelect API & margin style

packages/mcs-lite-ui/src/InputSelect/InputSelect.js
=> fix(ui): fix title with itemValueMapper function
